### PR TITLE
Added highlighting to string interpolation

### PR DESCRIPTION
**Pull request by AndreaCatalucci**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Can you provide some screen captures, to show what this will look like to a user? I'm happy with how string interpolation is highlighted currently, I'd like to see what this looks like first. thanks!

**Comment by AndreaCatalucci** [comment]
Well it was not working in my case (ruby and elixir)
here is a screenshot:
before 
screen shot 2015-05-12 at 20 42 05
after
screen shot 2015-05-12 at 20 38 50

**Comment by jonschlinkert** [comment]
it does look nice, interesting though that it still highlights on a syntax error.

**Comment by jonschlinkert** [comment]
I'll need to pull this down and test first, I'll report back after I have a chance to use it for it. If anyone else has any thoughts or feedback before I merge, please feel free to add comments

**Comment by AndreaCatalucci** [comment]
I think highlighting on syntax error is the right behavior.
Possible improvement is to render just the hello word in white such as variables, but did not get the chance to do it so far.

**Comment by jonschlinkert** [comment]
@AndreaCatalucci some changes have been made since this pr. I'm going to close for now, but I'd be happy to re-open if this is still desired and not working.

**Pull request closed without merging**
