### PR TITLE
adds support for ~~ strike-through text

### PR DESCRIPTION
**Pull request by SuperPaintman**
In addition to: [sublime-markdown-extended](https://github.com/jonschlinkert/sublime-markdown-extended/pull/110#issuecomment-166764353)

### CODE REVIEW

**Comment by SuperPaintman** [comment]
examplemd

**Comment by jonschlinkert** [comment]
that was fast! thanks again

**Comment by SuperPaintman** [comment]
Thank you for the better MD experience!

**Comment by jonschlinkert** [comment]
you are of course very welcome!

**Pull request merged**
