### PR TITLE
improve legibility of JSON strings and indent guides in Light theme

### PR DESCRIPTION
**Pull request by szupie**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Thanks, you would mind adding a screenshot of the changes?

**Comment by szupie** [comment]
Before: before
After: after

**Comment by jonschlinkert** [comment]
@szupie would you mind rebasing so I can merge? thanks

**Comment by szupie** [comment]
Hmm, looks like you had merged an earlier pull request, #76, that fixed the legibility issue. This set of changes completely overwrites those from that earlier PR. However, I believe the changes here improve scannability by keeping JSON strings a distinct colour without sacrificing legibility.

Before: 
monokai-before
After: 
monokai-after

**Comment by jonschlinkert** [comment]
> believe the changes here improve scannability by keeping JSON strings a distinct colour without sacrificing legibility.

agreed, thank you!

**Pull request merged**
